"docs":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "mkdocs.yml"

"secrets":
  - changed-files:
      - any-glob-to-any-file:
          - ".sops.yaml"
          - "secrets.yaml"
          - "**/*/*.enc.json"
          - "**/*/secrets.yaml"
          - "secrets/**/*"

"terraform":
  - changed-files:
      - any-glob-to-any-file:
          - "terraform/**/*"
