"sops secrets":
  - changed-files:
      - any-glob-to-any-file:
          - ".sops.yaml"
          - "secrets.yaml"
          - "**/*/*.enc.json"
          - "**/*/secrets.yaml"

"terraform":
  - changed-files:
      - any-glob-to-any-file:
          - "terraform/**/*"
