pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=ci/hercules/evaluation
      - check-success=ci/hercules/derivations
      - author=github-actions[bot]
      - head~=^update/(nixpkgs|sops-nix|hercules-ci-effects)-
    actions:
      merge:
        method: merge
      delete_head_branch: {}
