[
  "build01.nix-community.org"
  "build02.nix-community.org"
  "build03.nix-community.org"
  "build04.nix-community.org"
  "darwin02.nix-community.org"
  "darwin03.nix-community.org"
  "web01.nix-community.org"
  #"web02.nix-community.org"
]
