name: "Update flakes - input"
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      flakeInput:
        description: "flake input to update"
        required: true
        type: string
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # ensure workflow_dispatch only runs on master
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          inputs: ${{ inputs.flakeInput }}
      #- name: Enable Automerge
      #  run: gh pr merge --rebase --auto "${{ steps.update.outputs.pull-request-number }}"
      #  env:
      #    GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
